### ISSUE TITLE
What the script folder content is for?

### ISSUE THREAD

**Issue by Yahav** [fossar/HTMLawed#6]
I'll feel way more compatible if this repo would be 100% identical to the original.

**Comment by jtojnar** [comment]
It contains a script for updating the files in the repository. I agree that the directory name is not very descriptive, maybe something like `meta` or `maintenance` would be a better choice. We should also add a README to the directory, explaining what the scripts within are for and how they are used.

**Comment by Yahav** [comment]
So basically its a script that is used to fetch the latest version of the HTMLawed library?
I do believe that those shouldn't be part of the repository itself. it can be published at a different repo as a utility.

**Comment by j0k3r** [comment]
Infine that folder isn't delivered to the end user as it's ignored.
https://github.com/fossar/HTMLawed/blob/master/.gitattributes#L1
